#!/bin/bash
#
# Snap a webcam image for each commit

set -euo pipefail

dir=`xdg-user-dir PICTURES`
img="$dir/commits/$(date '+%Y')/commit-$(date '+%Y%m%d-%H%M%S').jpg"

mkdir -p `dirname $img`
fswebcam --quiet --no-banner --delay 1 --background "$img"
