#!/bin/bash
#
# Snap a webcam image for each commit

set -euo pipefail

[[ "$XDG_SESSION_TYPE" == "wayland" ]] || exit 0

root=$(xdg-user-dir PICTURES)
dir="$root/photos/cam/commits/$(date '+%Y')"
filename="$dir/commit-$(date '+%Y%m%d-%H%M%S').jpg"

mkdir -p "$dir"
fswebcam \
	--quiet \
	--device /dev/video2 \
	--no-banner \
	--delay 1 \
	--background \
	"$filename"
